// <auto-generated />
using System;
using GreenEnergy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenEnergy.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609125122_UpdateRelatorioTecnicoAndAlerts")]
    partial class UpdateRelatorioTecnicoAndAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Lido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.AnotacaoDispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DispositivoId");

                    b.ToTable("AnotacoesDispositivos");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.CacheClima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoIBGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("TempMax")
                        .HasColumnType("float");

                    b.Property<double>("TempMin")
                        .HasColumnType("float");

                    b.Property<double>("UmidadePercent")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CachesClima");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.CacheDadosIBGE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodigoIBGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopulacaoEstimada")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CachesDadosIBGE");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.CategoriaAparelho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasAparelhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Ar condicionado, aquecedores e ventiladores",
                            IconeUrl = "thermometer",
                            IsActive = true,
                            IsDeleted = false,
                            Nome = "Climatização"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Geladeira, fogão, micro-ondas, freezer e máquina de lavar",
                            IconeUrl = "kitchen",
                            IsActive = true,
                            IsDeleted = false,
                            Nome = "Eletrodomésticos"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Televisão, computador, roteador e consoles de videogame",
                            IconeUrl = "tv",
                            IsActive = true,
                            IsDeleted = false,
                            Nome = "Eletrônicos"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Lâmpadas LED, luminárias e fitas de LED",
                            IconeUrl = "lightbulb",
                            IsActive = true,
                            IsDeleted = false,
                            Nome = "Iluminação"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Carregadores, adaptadores e tomadas inteligentes",
                            IconeUrl = "plug",
                            IsActive = true,
                            IsDeleted = false,
                            Nome = "Outros / Uso Geral"
                        });
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("OperadorId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.ConfiguracaoAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NomeAPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesAPI");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PotenciaWatts")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TipoAparelho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeConsumidoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UnidadeConsumidoraId");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeConsumidoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeConsumidoraId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvaliacaoObs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DesligarAoEstourar")
                        .HasColumnType("bit");

                    b.Property<bool>("DispositivoDesligadoPorMeta")
                        .HasColumnType("bit");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoMeta")
                        .HasColumnType("int");

                    b.Property<double>("ValorLimite")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("OperadorId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Perfis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Documento = "000.000.000-00",
                            IsActive = true,
                            IsDeleted = false,
                            Telefone = "(00) 00000-0000",
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.RelatorioTecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<string>("SolucaoRecomendada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoOcorrencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("OperadorId");

                    b.ToTable("RelatoriosTecnicos");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModeloSensor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoSinal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId")
                        .IsUnique()
                        .HasFilter("[DispositivoId] IS NOT NULL");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bandeira")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("ValorKWh")
                        .HasColumnType("float");

                    b.Property<DateTime>("VigenciaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bandeira = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ValorKWh = 0.65000000000000002,
                            VigenciaInicio = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Telemetria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumoKWh")
                        .HasColumnType("float");

                    b.Property<double>("CorrenteA")
                        .HasColumnType("float");

                    b.Property<int?>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<double>("TensaoV")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("SensorId");

                    b.ToTable("Telemetrias");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.UnidadeConsumidora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoIBGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoImovel")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UnidadesConsumidoras");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@greenenergy.com",
                            IsActive = true,
                            IsDeleted = false,
                            Nome = "Administrador Geral",
                            Role = 0,
                            SenhaHash = "$2a$11$X7NajVOMby0KhlEqKxX73OZwgyitZql2gVqRenX7VCu03gjsq4lcm"
                        });
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Alerta", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Dispositivo", "Dispositivo")
                        .WithMany("Alertas")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.AnotacaoDispositivo", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenEnergy.API.Models.Entities.Dispositivo", "Dispositivo")
                        .WithMany("Anotacoes")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Usuario")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Chamado", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Cliente")
                        .WithMany("ChamadosCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenEnergy.API.Models.Entities.Dispositivo", "Dispositivo")
                        .WithMany("Chamados")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Operador")
                        .WithMany("ChamadosOperador")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Dispositivo");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Dispositivo", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.CategoriaAparelho", "Categoria")
                        .WithMany("Dispositivos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenEnergy.API.Models.Entities.UnidadeConsumidora", "UnidadeConsumidora")
                        .WithMany("Dispositivos")
                        .HasForeignKey("UnidadeConsumidoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadeConsumidora");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Endereco", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.UnidadeConsumidora", "UnidadeConsumidora")
                        .WithOne("Endereco")
                        .HasForeignKey("GreenEnergy.API.Models.Entities.Endereco", "UnidadeConsumidoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeConsumidora");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Meta", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Dispositivo", "Dispositivo")
                        .WithMany("Metas")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Operador")
                        .WithMany("MetasAvaliadas")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dispositivo");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Perfil", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Usuario")
                        .WithOne("Perfil")
                        .HasForeignKey("GreenEnergy.API.Models.Entities.Perfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.RelatorioTecnico", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Chamado", "Chamado")
                        .WithMany("RelatoriosTecnicos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Sensor", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Dispositivo", "Dispositivo")
                        .WithOne("Sensor")
                        .HasForeignKey("GreenEnergy.API.Models.Entities.Sensor", "DispositivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Telemetria", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Dispositivo", null)
                        .WithMany("Telemetrias")
                        .HasForeignKey("DispositivoId");

                    b.HasOne("GreenEnergy.API.Models.Entities.Sensor", "Sensor")
                        .WithMany("Telemetrias")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.UnidadeConsumidora", b =>
                {
                    b.HasOne("GreenEnergy.API.Models.Entities.Usuario", "Usuario")
                        .WithMany("UnidadesConsumidoras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.CategoriaAparelho", b =>
                {
                    b.Navigation("Dispositivos");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Chamado", b =>
                {
                    b.Navigation("RelatoriosTecnicos");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Dispositivo", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Anotacoes");

                    b.Navigation("Chamados");

                    b.Navigation("Metas");

                    b.Navigation("Sensor");

                    b.Navigation("Telemetrias");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Sensor", b =>
                {
                    b.Navigation("Telemetrias");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.UnidadeConsumidora", b =>
                {
                    b.Navigation("Dispositivos");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("GreenEnergy.API.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("AuditLogs");

                    b.Navigation("ChamadosCliente");

                    b.Navigation("ChamadosOperador");

                    b.Navigation("MetasAvaliadas");

                    b.Navigation("Perfil");

                    b.Navigation("UnidadesConsumidoras");
                });
#pragma warning restore 612, 618
        }
    }
}
